### PR TITLE
Update deps to latest

### PR DESCRIPTION
**Pull request by MangelMaxime**
This changes are needed for my next PR to Ionide.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak Just a friendly ping :)

**Comment by Krzysztof-Cieslak** [comment]
Hey, sorry for delay - I'll take a look at it when I'm back from Oslo next week.

**Comment by MangelMaxime** [comment]
Ok no problem :)

Enjoy, your trip and the conference :)

**Comment by MangelMaxime** [comment]
I am trying my luck today again :)

@Krzysztof-Cieslak 

*This is because, I would like to have HTML-To-Elmish inside Ionide for NDCOslo if possible.*

**Comment by MangelMaxime** [comment]
Thank you, I will send a PR to Ionide to update it with master version of this branch and HTML-To-Elmish.

**Pull request merged**
