### PR TITLE
add getFsiFullPathWin to find path of Fsi.exe on Windows

### PR DESCRIPTION
**Pull request by oxxa**
Added function getFsiFullPathWin for use in Fsi.fs of ionide-vscode-fsharp (see matching pull request there)

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Does it actually compile and work if FSI is not in PATH? I didn't know that Fable supports `System.Environment` namespace.

**Comment by oxxa** [comment]
I must admit I had a hard time working out how to install and test the extension as a whole so I tested the code in isolation with the expected inputs.  It should function like this:  1) called with an exe name that exists on PATH (or in the standard install dir) then it will return that found path + the exe name, 2) called with exe name which is not found on PATH (or the install dir) then just returns the exe name that was passed in (in this case it behaves as the orginal calling code did).
It was my intent that this function is only called when running on Windows (see Process.IsWin check in Ionide-vscode-fsharp PR) so I expect all .Net system calls to be valid.

**Comment by oxxa** [comment]
oops! accidentally closed it.

**Comment by oxxa** [comment]
I see your point, I had not appreciated the pipeline involved with Fable - which I was not aware of but I am very impressed by - such that the fs code is processed to js.  I will close this PR until I can become more familiar with that and test it produces valid js.  Thanks.

**Comment by Krzysztof-Cieslak** [comment]
You need to use functions from Node.js `process` module - https://nodejs.org/api/process.html instead of calls to `System.Environment` and everything should be OK.

For easy testing - (assuming you have node installed) just clone, `ionide-vscode-fsharp`, run `build.cmd Build`, open repository folder in VS Code, press F5 - it should start experimental instance with changes loaded.

**Comment by oxxa** [comment]
Is there another step I'm missing?  After running build.cmd Build and starting the experimental instance and opening a fs file it hits an exception trying to "spawn ionide-vscode-fsharp\release/bin/FsAutoComplete.Suave.exe.  However I see that that release\bin folder is empty.

**Comment by Krzysztof-Cieslak** [comment]
I think `build.cmd Build` should copy everything. Hmm... I'll check it when I'll have good internet connection ( on the airport right now). Meanwhile pinging @cloudroutine, maybe he'll know what's wrong.

**Comment by cloudRoutine** [comment]
I just deleted release and ran build again on my machine with F5 in vscode, everything gets copied to release, launches, and is working fine

**Comment by oxxa** [comment]
Hmm, deleting release and F5'ing has done the trick, thanks!

**Comment by oxxa** [comment]
I would like to able to access the 'programfiles(x86)' environment variable.  Can anyone think of a way to do this, Fable doesn't yet support System.Environment.GetEnvironmentVariable and I can't use "Process.env?VARNAME" due to the ()'s in  'programfiles(x86)'.  My attempted solution which used reflection to get the prop value from Process.env won't work either as Fable doesn't do 'GetProperty'.

**Comment by oxxa** [comment]
I think it is better to keep this change to the ionide vscode repo so I have closed this one.

**Pull request closed without merging**
